// app/api/sinco/route.ts
import { NextResponse } from 'next/server';


const HUBSPOT_TOKEN = process.env.HUBSPOT_API_KEY!;
const propertiesEndpoint = 'https://api.hubapi.com/crm/v3/properties/deals';

const propertiesArray = [
"tramite_FEFI_compromiso",
"tramite_OSFP_compromiso",
"tramite_PUEQ_compromiso",
"tramite_RADC_compromiso",
"tramite_RCDN_compromiso",
"tramite_RDSB_compromiso",
"tramite_RECC_compromiso",
"tramite_REDF_compromiso",
"tramite_REDN_compromiso",
"tramite_REFF_compromiso",
"tramite_RVBB_compromiso",
"tramite_EEFF_compromiso",
"tramite_EEFN_compromiso",
"tramite_FAPC_compromiso",
"tramite_ODSE_compromiso",
"tramite_EEAF_compromiso",
"tramite_ECNO_compromiso",
"tramite_APSB_compromiso",
"tramite_DSCC_compromiso",
"tramite_CEDE_compromiso",
"tramite_CEHB_compromiso",
"tramite_REEB_compromiso",
"tramite_LEIN_compromiso",
"tramite_PRCR_compromiso",
"tramite_APEF_compromiso",
"tramite_FEIF_compromiso",
"tramite_FEBP_compromiso",
"tramite_FIEN_compromiso",
"tramite_EDEF_compromiso",
"tramite_ENFI_compromiso",
"tramite_FPCV_compromiso",
"tramite_PV_compromiso",
"tramite_FPRO_compromiso",
"tramite_RDCR_compromiso",
"tramite_REFI_compromiso",
"tramite_EPVE_compromiso",
"tramite_APCR_compromiso",
"tramite_LLPV_compromiso",
"tramite_PSCA_compromiso",
"tramite_FOTS_compromiso",
"tramite_EEPM_compromiso",
"tramite_FOT2_compromiso",
"tramite_CAGN_compromiso",
"tramite_LPMJ_compromiso",
"tramite_PGAV_compromiso",
"tramite_EPCF_compromiso",
"tramite_LPMF_compromiso",
"tramite_FESC_compromiso",
"tramite_OEAN_compromiso",
"tramite_EDCS_compromiso",
"tramite_FESE_compromiso",
"tramite_FIEC_compromiso",
"tramite_SPPR_compromiso",
"tramite_ECVT_compromiso",
"tramite_PPR_compromiso",
"tramite_DEEF_compromiso",
"tramite_PEPH_compromiso",
"tramite_RCH_compromiso",
"tramite_REBC_compromiso",
"tramite_RERG_compromiso",
"tramite_EFBC_compromiso",
"tramite_DMCY_compromiso",
"tramite_RFCC_compromiso",
"tramite_RMCY_compromiso",
"tramite_EACN_compromiso",
"tramite_FPYC_compromiso",
"tramite_IREG_compromiso",
"tramite_ENIN_compromiso",
"tramite_FEIN_compromiso",
"tramite_SREG_compromiso",
"tramite_FEEB_compromiso",
"tramite_EECN_compromiso",
"tramite_IERG_compromiso",
"tramite_LLER_compromiso",
"tramite_EELC_compromiso",
"tramite_VBEB_compromiso",
"tramite_REDC_compromiso",
"tramite_DECR_compromiso",
"tramite_CPCF_compromiso",
"tramite_EESV_compromiso",
"tramite_FEBC_compromiso",
"tramite_FEF_compromiso",
"tramite_LCEB_compromiso",
"tramite_SAVA_compromiso",
"tramite_VCSA_compromiso",
"tramite_EEBC_compromiso",
"tramite_CDAT_compromiso",
"tramite_SEDT_compromiso",
"tramite_RAEB_compromiso",
"tramite_RESE_compromiso",
"tramite_ULTA_compromiso",
"tramite_FEFI_cumplimiento",
"tramite_OSFP_cumplimiento",
"tramite_PUEQ_cumplimiento",
"tramite_RADC_cumplimiento",
"tramite_RCDN_cumplimiento",
"tramite_RDSB_cumplimiento",
"tramite_RECC_cumplimiento",
"tramite_REDF_cumplimiento",
"tramite_REDN_cumplimiento",
"tramite_REFF_cumplimiento",
"tramite_RVBB_cumplimiento",
"tramite_EEFF_cumplimiento",
"tramite_EEFN_cumplimiento",
"tramite_FAPC_cumplimiento",
"tramite_ODSE_cumplimiento",
"tramite_EEAF_cumplimiento",
"tramite_ECNO_cumplimiento",
"tramite_APSB_cumplimiento",
"tramite_DSCC_cumplimiento",
"tramite_CEDE_cumplimiento",
"tramite_CEHB_cumplimiento",
"tramite_REEB_cumplimiento",
"tramite_LEIN_cumplimiento",
"tramite_PRCR_cumplimiento",
"tramite_APEF_cumplimiento",
"tramite_FEIF_cumplimiento",
"tramite_FEBP_cumplimiento",
"tramite_FIEN_cumplimiento",
"tramite_EDEF_cumplimiento",
"tramite_ENFI_cumplimiento",
"tramite_FPCV_cumplimiento",
"tramite_PV_cumplimiento",
"tramite_FPRO_cumplimiento",
"tramite_RDCR_cumplimiento",
"tramite_REFI_cumplimiento",
"tramite_EPVE_cumplimiento",
"tramite_APCR_cumplimiento",
"tramite_LLPV_cumplimiento",
"tramite_PSCA_cumplimiento",
"tramite_FOTS_cumplimiento",
"tramite_EEPM_cumplimiento",
"tramite_FOT2_cumplimiento",
"tramite_CAGN_cumplimiento",
"tramite_LPMJ_cumplimiento",
"tramite_PGAV_cumplimiento",
"tramite_EPCF_cumplimiento",
"tramite_LPMF_cumplimiento",
"tramite_FESC_cumplimiento",
"tramite_OEAN_cumplimiento",
"tramite_EDCS_cumplimiento",
"tramite_FESE_cumplimiento",
"tramite_FIEC_cumplimiento",
"tramite_SPPR_cumplimiento",
"tramite_ECVT_cumplimiento",
"tramite_PPR_cumplimiento",
"tramite_DEEF_cumplimiento",
"tramite_PEPH_cumplimiento",
"tramite_RCH_cumplimiento",
"tramite_REBC_cumplimiento",
"tramite_RERG_cumplimiento",
"tramite_EFBC_cumplimiento",
"tramite_DMCY_cumplimiento",
"tramite_RFCC_cumplimiento",
"tramite_RMCY_cumplimiento",
"tramite_EACN_cumplimiento",
"tramite_FPYC_cumplimiento",
"tramite_IREG_cumplimiento",
"tramite_ENIN_cumplimiento",
"tramite_FEIN_cumplimiento",
"tramite_SREG_cumplimiento",
"tramite_FEEB_cumplimiento",
"tramite_EECN_cumplimiento",
"tramite_IERG_cumplimiento",
"tramite_LLER_cumplimiento",
"tramite_EELC_cumplimiento",
"tramite_VBEB_cumplimiento",
"tramite_REDC_cumplimiento",
"tramite_DECR_cumplimiento",
"tramite_CPCF_cumplimiento",
"tramite_EESV_cumplimiento",
"tramite_FEBC_cumplimiento",
"tramite_FEF_cumplimiento",
"tramite_LCEB_cumplimiento",
"tramite_SAVA_cumplimiento",
"tramite_VCSA_cumplimiento",
"tramite_EEBC_cumplimiento",
"tramite_CDAT_cumplimiento",
"tramite_SEDT_cumplimiento",
"tramite_RAEB_cumplimiento",
"tramite_RESE_cumplimiento",
"tramite_ULTA_cumplimiento"
]


// GET method - Sync contacts with "cotizacion pedida" status from HubSpot to Sinco
export async function GET() {
    const updates = Promise.all(
        propertiesArray.map(async (propertie) => {
            const properties = {
                name: propertie.toLowerCase(),
                label: propertie.toLowerCase(),
                type: "string",
                fieldType: "text",
                groupName: "deal_activity",
                description: "Tramite de sinco",
                options: []
            }
            const response = await fetch(propertiesEndpoint, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${HUBSPOT_TOKEN}`,
                },
                body: JSON.stringify(properties),
            });

            const data = await response.json();

            if (!response.ok) {
            console.error('HubSpot API error:', data);
            // Return HubSpot's error message to the client
                return NextResponse.json(data, { status: response.status });
            }

            return {
                created : propertie.toLowerCase(),
            }
        })
    )

    return NextResponse.json(updates, { status: 200 });
}